### ISSUE TITLE
Code leaks

### ISSUE THREAD

**Issue by idx0** [CIVA-Lab/solar-position-calculator#4]
I downloaded this solar position repo to try out some sun positioning for lighting in a hobby program I am working on.  While adapting your code I noticed it leaks all over the place.  For example, every time you call:

SolarPositionCalculation *spc = new SolarPositionCalculation();

Inside TimeLocation.cpp for example, this memory is never freed.

**Comment by ekincanufuktepe** [comment]
Hi @idx0, yeah you are right, good catch. A rookie mistake of mine, I haven't tested with Valgrind yet. I will push a new commit today. Thanks!

**Comment by ekincanufuktepe** [comment]
Hey Steve @idx0, thanks again for the heads up. The solar-position-calculator should be free of memory leaks now. The fixes are in the commit 3dab8e6f7aa7f67d5ed8df9805a98759258a2e08.
